### ISSUE TITLE
Create recipe card (front side only)

### ISSUE THREAD

**Issue by AmandaBoo** [AmandaBoo/Project-Not-Boba#29]
**Chef's hat Icon**
- There is a chef's hat icon below the Custom progress bar that when clicked switches to a text field that allows user to input how many they've created. 
- Users will be allowed to cancel or apply their changes, and their current proficiency/custom quantity will be updated with the new values should the click apply
- The text field has a default value of 0
- negative values are not allowed in the field
![image](https://user-images.githubusercontent.com/32873716/127246473-d4309e29-1d9f-43db-9b58-05d628218699.png)

**Comment by Oskar-Alyn** [comment]
Should:
- [ ] Have progress bar for the two completion fields, mastery and custom
- [ ] Have an actual toggle displayed for the toggle button
- [ ] Summary should collate like types (cold-cut-platter would cause multiple meat cards to appear)
- [ ] Needs cook option
- [ ] Needs pencil option to flip to edit side
- [ ] Needs to change color to reflect rarity

**Comment by Oskar-Alyn** [comment]
Progress bar mostly works:
- [ ] : Add partial progress system

Bottom two should move to the backside

**Comment by AmandaBoo** [comment]
Not relevant anymore
